//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contact.
        /// </summary>
        public static string AddContact {
            get {
                return ResourceManager.GetString("AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot exceed 200 characters.
        /// </summary>
        public static string AddressLengthError {
            get {
                return ResourceManager.GetString("AddressLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Work.
        /// </summary>
        public static string AddWork {
            get {
                return ResourceManager.GetString("AddWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalculationError.
        /// </summary>
        public static string CalculationError {
            get {
                return ResourceManager.GetString("CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        public static string ContactEmailInvalid {
            get {
                return ResourceManager.GetString("ContactEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        public static string ContactList {
            get {
                return ResourceManager.GetString("ContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name is required.
        /// </summary>
        public static string ContactNameError {
            get {
                return ResourceManager.GetString("ContactNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name must be between 2 and 50 characters.
        /// </summary>
        public static string ContactNameLength {
            get {
                return ResourceManager.GetString("ContactNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name cannot exceed 50 characters.
        /// </summary>
        public static string ContactNameLengthError {
            get {
                return ResourceManager.GetString("ContactNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact name is required.
        /// </summary>
        public static string ContactNameRequired {
            get {
                return ResourceManager.GetString("ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format.
        /// </summary>
        public static string ContactPhoneInvalid {
            get {
                return ResourceManager.GetString("ContactPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirm Title.
        /// </summary>
        public static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contact.
        /// </summary>
        public static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you sure delete the expense?.
        /// </summary>
        public static string DeleteExpenseConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteExpenseConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you sure delete the work?.
        /// </summary>
        public static string DeleteWorkConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteWorkConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you sure delete the Contact record?.
        /// </summary>
        public static string DeleteWorkContactConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteWorkContactConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contact.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Work.
        /// </summary>
        public static string EditWork {
            get {
                return ResourceManager.GetString("EditWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        public static string ExpenseAmountError {
            get {
                return ResourceManager.GetString("ExpenseAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than 0.
        /// </summary>
        public static string ExpenseAmountRangeError {
            get {
                return ResourceManager.GetString("ExpenseAmountRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 200 characters.
        /// </summary>
        public static string ExpenseDescriptionError {
            get {
                return ResourceManager.GetString("ExpenseDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is required.
        /// </summary>
        public static string ExpenseTimeError {
            get {
                return ResourceManager.GetString("ExpenseTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializationError.
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data Error.
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format.
        /// </summary>
        public static string PhoneError {
            get {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string PreStart {
            get {
                return ResourceManager.GetString("PreStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        public static string QQ {
            get {
                return ResourceManager.GetString("QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ number must be 5-11 digits.
        /// </summary>
        public static string QQError {
            get {
                return ResourceManager.GetString("QQError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ Invalid fail.
        /// </summary>
        public static string QQInvalid {
            get {
                return ResourceManager.GetString("QQInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Amount.
        /// </summary>
        public static string ReceivedAmount {
            get {
                return ResourceManager.GetString("ReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark cannot exceed 500 characters.
        /// </summary>
        public static string RemarkLengthError {
            get {
                return ResourceManager.GetString("RemarkLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contacts....
        /// </summary>
        public static string SearchContacts {
            get {
                return ResourceManager.GetString("SearchContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Error.
        /// </summary>
        public static string SearchError {
            get {
                return ResourceManager.GetString("SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search tags....
        /// </summary>
        public static string SearchTags {
            get {
                return ResourceManager.GetString("SearchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tags.
        /// </summary>
        public static string SelectTags {
            get {
                return ResourceManager.GetString("SelectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2} characters.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name already exists.
        /// </summary>
        public static string TagNameExists {
            get {
                return ResourceManager.GetString("TagNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name must be between 2 and 50 characters.
        /// </summary>
        public static string TagNameLength {
            get {
                return ResourceManager.GetString("TagNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name is required.
        /// </summary>
        public static string TagNameRequired {
            get {
                return ResourceManager.GetString("TagNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedAt.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wechat.
        /// </summary>
        public static string Wechat {
            get {
                return ResourceManager.GetString("Wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat ID cannot exceed 50 characters.
        /// </summary>
        public static string WechatLengthError {
            get {
                return ResourceManager.GetString("WechatLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work amount must be greater than 0.
        /// </summary>
        public static string WorkAmountRange {
            get {
                return ResourceManager.GetString("WorkAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work amount is required.
        /// </summary>
        public static string WorkAmountRequired {
            get {
                return ResourceManager.GetString("WorkAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string WorkDescription {
            get {
                return ResourceManager.GetString("WorkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 500 characters.
        /// </summary>
        public static string WorkDescriptionError {
            get {
                return ResourceManager.GetString("WorkDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Details.
        /// </summary>
        public static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work End Date.
        /// </summary>
        public static string WorkEndDate {
            get {
                return ResourceManager.GetString("WorkEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be later than start time.
        /// </summary>
        public static string WorkEndTimeError {
            get {
                return ResourceManager.GetString("WorkEndTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time format is invalid.
        /// </summary>
        public static string WorkEndTimeInvalid {
            get {
                return ResourceManager.GetString("WorkEndTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be later than start time.
        /// </summary>
        public static string WorkEndTimeMustLaterThanStart {
            get {
                return ResourceManager.GetString("WorkEndTimeMustLaterThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual completion time format is invalid.
        /// </summary>
        public static string WorkExceptionTimeInvalid {
            get {
                return ResourceManager.GetString("WorkExceptionTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual completion time must be later than start time.
        /// </summary>
        public static string WorkExceptionTimeMustLaterThanStart {
            get {
                return ResourceManager.GetString("WorkExceptionTimeMustLaterThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work List.
        /// </summary>
        public static string WorkList {
            get {
                return ResourceManager.GetString("WorkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WorkName {
            get {
                return ResourceManager.GetString("WorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work name is required.
        /// </summary>
        public static string WorkNameError {
            get {
                return ResourceManager.GetString("WorkNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work name cannot exceed 50 characters.
        /// </summary>
        public static string WorkNameLengthError {
            get {
                return ResourceManager.GetString("WorkNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work name required.
        /// </summary>
        public static string WorkNameRequired {
            get {
                return ResourceManager.GetString("WorkNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work StartDate.
        /// </summary>
        public static string WorkStartDate {
            get {
                return ResourceManager.GetString("WorkStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is required.
        /// </summary>
        public static string WorkStartTimeError {
            get {
                return ResourceManager.GetString("WorkStartTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time format is invalid.
        /// </summary>
        public static string WorkStartTimeInvalid {
            get {
                return ResourceManager.GetString("WorkStartTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work StartTime Required.
        /// </summary>
        public static string WorkStartTimeRequired {
            get {
                return ResourceManager.GetString("WorkStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required.
        /// </summary>
        public static string WorkStatusError {
            get {
                return ResourceManager.GetString("WorkStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work status is required.
        /// </summary>
        public static string WorkStatusRequired {
            get {
                return ResourceManager.GetString("WorkStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work title must be between 2 and 100 characters.
        /// </summary>
        public static string WorkTitleLength {
            get {
                return ResourceManager.GetString("WorkTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work title is required.
        /// </summary>
        public static string WorkTitleRequired {
            get {
                return ResourceManager.GetString("WorkTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount format is invalid.
        /// </summary>
        public static string WorkTotalMoneyInvalid {
            get {
                return ResourceManager.GetString("WorkTotalMoneyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount must be greater than or equal to 0.
        /// </summary>
        public static string WorkTotalMoneyRange {
            get {
                return ResourceManager.GetString("WorkTotalMoneyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount is required.
        /// </summary>
        public static string WorkTotalMoneyRequired {
            get {
                return ResourceManager.GetString("WorkTotalMoneyRequired", resourceCulture);
            }
        }
    }
}
