//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMR.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMR.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid email format 的本地化字符串。
        /// </summary>
        public static string ContactEmailInvalid {
            get {
                return ResourceManager.GetString("ContactEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact name must be between 2 and 50 characters 的本地化字符串。
        /// </summary>
        public static string ContactNameLength {
            get {
                return ResourceManager.GetString("ContactNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact name is required 的本地化字符串。
        /// </summary>
        public static string ContactNameRequired {
            get {
                return ResourceManager.GetString("ContactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid phone number format 的本地化字符串。
        /// </summary>
        public static string ContactPhoneInvalid {
            get {
                return ResourceManager.GetString("ContactPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatedAt 的本地化字符串。
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InActive 的本地化字符串。
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Required 的本地化字符串。
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is required 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be between {1} and {2} characters 的本地化字符串。
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag name already exists 的本地化字符串。
        /// </summary>
        public static string TagNameExists {
            get {
                return ResourceManager.GetString("TagNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag name must be between 2 and 50 characters 的本地化字符串。
        /// </summary>
        public static string TagNameLength {
            get {
                return ResourceManager.GetString("TagNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag name is required 的本地化字符串。
        /// </summary>
        public static string TagNameRequired {
            get {
                return ResourceManager.GetString("TagNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdatedAt 的本地化字符串。
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work amount must be greater than 0 的本地化字符串。
        /// </summary>
        public static string WorkAmountRange {
            get {
                return ResourceManager.GetString("WorkAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work amount is required 的本地化字符串。
        /// </summary>
        public static string WorkAmountRequired {
            get {
                return ResourceManager.GetString("WorkAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work title must be between 2 and 100 characters 的本地化字符串。
        /// </summary>
        public static string WorkTitleLength {
            get {
                return ResourceManager.GetString("WorkTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work title is required 的本地化字符串。
        /// </summary>
        public static string WorkTitleRequired {
            get {
                return ResourceManager.GetString("WorkTitleRequired", resourceCulture);
            }
        }
    }
}
